# Generated by Django 3.2.3 on 2022-01-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_ca', '0006_alter_extendeduser_id'),
        ('registration_ca', '0008_auto_20211221_1654'),
    ]

    operations = [
    ]
