# Generated by Django 3.2.3 on 2022-01-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_ca', '0009_merge_20220108_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azeo_id_user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
