# Generated by Django 3.2.3 on 2022-03-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemathon_questions',
            name='question1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chemathon_questions',
            name='question2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chemathon_questions',
            name='question3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chemathon_questions',
            name='question4',
            field=models.IntegerField(null=True),
        ),
    ]
