# Generated by Django 3.2.3 on 2022-03-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemathon', '0002_auto_20220303_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemathon_questions',
            name='submitted_at',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
