# Generated by Django 3.2.3 on 2022-03-17 17:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemathon', '0004_chemathonuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemathon_questions_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', ckeditor_uploader.fields.RichTextUploadingField()),
                ('q2', ckeditor_uploader.fields.RichTextUploadingField()),
                ('q3', ckeditor_uploader.fields.RichTextUploadingField()),
                ('q4', ckeditor_uploader.fields.RichTextUploadingField()),
                ('q5', ckeditor_uploader.fields.RichTextUploadingField()),
                ('q6', ckeditor_uploader.fields.RichTextUploadingField()),
                ('q7', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.AddField(
            model_name='chemathon_questions',
            name='question5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chemathon_questions',
            name='question6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chemathon_questions',
            name='question7',
            field=models.IntegerField(null=True),
        ),
    ]
