# Generated by Django 3.2.6 on 2022-03-17 22:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemathon', '0005_auto_20220317_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemathon_questions_admin',
            name='q1',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='chemathon_questions_admin',
            name='q2',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='chemathon_questions_admin',
            name='q3',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='chemathon_questions_admin',
            name='q4',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='chemathon_questions_admin',
            name='q5',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='chemathon_questions_admin',
            name='q6',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='chemathon_questions_admin',
            name='q7',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
